
#==============================================================================#

name = "BitPackedInstances"
uuid = "4367d3ae-5d96-4441-94f8-c197a4364aab"
authors = ["BitPackedInstances contributors"]
version = "0.2.0"

[compat]
julia = "1.12"

#==============================================================================#
